### ISSUE TITLE
New Netflix module not working

### ISSUE THREAD

**Issue by krishnasinghvaid123** [Mickey758/Calani-AIO#15]
I added some working netflix accounts in the combolists to check if the module is working or not.
But sadly, its showing all accounts are bad. Couldn't find even one 2FA or working account in around 600combolist

**Comment by SkyN9ne** [comment]
Not the developer but a 600 combolist is extremely small. In the past when I did these actively I usually used at least 500k+ combolists but upto 10 million

**Comment by ImInTheICU** [comment]
> Not the developer but a 600 combolist is extremely small. In the past when I did these actively I usually used at least 500k+ combolists but upto 10 million

How would this matter?

**Comment by Mickey758** [comment]
U need hq proxies to use this module
