### ISSUE TITLE
DISPLAY TYPE LOG [SUGGESTION]

### ISSUE THREAD

**Issue by snoopyxz** [Mickey758/Calani-AIO#16]
Hi, can u in the future add log display type please

Like this:
![imagem](https://user-images.githubusercontent.com/104867141/209416861-e32c1446-85ca-462c-9da5-7a89a2e2d15a.png)

**Comment by Mickey758** [comment]
Will take into consideration

**Comment by Mickey758** [comment]
Added

https://github.com/Mickey758/Calani-AIO/releases/tag/v1.0.4
