### ISSUE TITLE
Change Proxy Type

### ISSUE THREAD

**Issue by PierrunoYT** [Mickey758/Calani-AIO#2]
Can you add the option to change proxy type to socks 4 or 5 or may the auto detect wich type of proxy it is

**Comment by Mickey758** [comment]
You can already change that in the settings or in the config file

**Comment by PierrunoYT** [comment]
Can you add a Combo Scraper?

**Comment by Hail2Hydra** [comment]
@PierrunoYT 

Youll never make it anywhere trying to use socks 4/5 when 99% of sites Only support HTTP/s which is the exact reason the creator made it to use HTTP/s
