### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Zaklife** [Mickey758/Calani-AIO#21]
hello i receive this error when i run pip3 install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32

**Comment by Mickey758** [comment]
what platform are you on?

**Comment by GDMgmer3992** [comment]
try using pip install -r requirements.txt

**Comment by GDMgmer3992** [comment]
and use python 3.10
