### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by MrShadowDev** [Mickey758/Calani-AIO#29]
**1. Make it faster.
2. Add more links to scrape proxies (more than 50% of up to day scrapped proxies are dead)
3. Add more modules (Netflix, PayPal...)
4. Do a better UI (make the console better bro its good but i thinkk you can do it better :D**

**Comment by Claqzwtf** [comment]
[Kanao-AIO](https://github.com/MrShadowDev/Kanao-AIO)

quit skidding lol ur a loser

**Comment by Mickey758** [comment]
LMFAO
