### ISSUE TITLE
when i use the checker it gives only errors

### ISSUE THREAD

**Issue by jacob25-pro** [Mickey758/Calani-AIO#32]
i load my proxies and combos in and it keeps giving errors, no hits no bad only errors and i have use many different proxies and combo lists so its not the combos or proxies.

**Comment by Mickey758** [comment]
What module are you experiencing this issue on

**Comment by beben147** [comment]
Hello i have the same problem

**Comment by jacob25-pro** [comment]
> What module are you experiencing this issue on
BWW is showing no hits when im literally checking a list of my BWW hits. Steam has a cpm of 5 and is giving 10k errors by still works. Let me know how I can get this bww checker to work somehow.
