### ISSUE TITLE
Netflix broken

### ISSUE THREAD

**Issue by GifXx** [Mickey758/Calani-AIO#5]
I put 5good netflix but checker said its bad but its working wtf :)

**Comment by chekamarue** [comment]
netflix need paid/rotating proxies wtf

**Comment by Mickey758** [comment]
What is your proxy provider?

**Comment by GifXx** [comment]
I am using https://proxyscrape.com/free-proxy-list http

**Comment by Mickey758** [comment]
you are using free proxies to check netflix, thats ur problem right there.
