### ISSUE TITLE
Netflix Module

### ISSUE THREAD

**Issue by AhanafMahmud** [Mickey758/Calani-AIO#9]
Did u remove netflix module.Add the following module=Spotify,YT Premium,minecraft
plus i love ur work this checkers works as butter.All i can say keep up the good work
btw when is the next update is coming

**Comment by Mickey758** [comment]
Hey, yes the netflix module was removed as it skipped hits a lot. I would like to add the netflix module again but i will need to get a different api, and im not sure how long that will take, I will however, take a look at the modules you mentioned. I don't like to update too frequently, so maybe a week or 2 will be an update.
